backend:
  name: github
  repo: srinadia/sibukbersantai.github.io
  branch: main
  base_url: https://decap-cms-git-master-decaporg.vercel.app
  auth_endpoint: auth

media_folder: assets/images
public_folder: /assets/images

collections:
  - name: content
    label: Konten
    files:
      - name: settings
        label: Pengaturan Situs
        file: data/settings.json
        format: json
        fields:
          - label: "Judul"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
          - label: "Intro"
            name: "intro"
            widget: "text"
          - label: "Email Kontak"
            name: "contactEmail"
            widget: "string"
          - label: "Instagram"
            name: "instagram"
            widget: "string"
      
      - name: works
        label: Karya
        file: data/works.json
        format: json
        fields:
          - label: "Daftar Karya"
            name: "works"
            widget: "list"
            fields:
              - label: "Judul"
                name: "title"
                widget: "string"
              - label: "Deskripsi"
                name: "description"
                widget: "text"
              - label: "URL"
                name: "url"
                widget: "string"
                required: false
